version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: harvesthub-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: harvesthub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6-jammy
    container_name: harvesthub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: harvesthub-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  mongodb_data:
