/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hddhezmwewapnhduhvxr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZGhlem13ZXdhcG5oZHVodnhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg4MjYyNTksImV4cCI6MjA4NDQwMjI1OX0.zk-nX5jMGzO13b-dyL9IQcckm6XJSEyRJrGEL2jMKps"